{
  "packageName": "javax.naming.event",
  "simpleName": "NamingExceptionEvent",
  "moduleName": "java.naming",
  "type": "CLASS",
  "superClass": {
    "name": "java.util.EventObject",
    "type": "Class"
  },
  "members": [
    {
      "returnType": {
        "name": "javax.naming.NamingException",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getException",
      "comment": "Retrieves the exception that was thrown.",
      "tagMap": {
        "return": [
          "The exception that was thrown."
        ]
      }
    },
    {
      "returnType": {
        "name": "javax.naming.event.EventContext",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getEventContext",
      "comment": "Retrieves the EventContext that fired this event. This returns the same object as EventObject.getSource().",
      "tagMap": {
        "return": [
          "The non-null \n\u003ccode\u003eEventContext\u003c/code\u003e that fired this event."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "javax.naming.event.NamingListener",
            "type": "Class"
          },
          "field": {
            "name": "listener"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "dispatch",
      "comment": "Invokes the namingExceptionThrown() method on a listener using this event.",
      "tagMap": {
        "param": [
          "\u003ccode\u003elistener\u003c/code\u003e - The non-null naming listener on which to invoke the method."
        ]
      }
    },
    {
      "parameters": [
        {
          "type": {
            "name": "javax.naming.event.EventContext",
            "type": "Class"
          },
          "field": {
            "name": "source"
          }
        },
        {
          "type": {
            "name": "javax.naming.NamingException",
            "type": "Class"
          },
          "field": {
            "name": "exc"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs an instance of NamingExceptionEvent using the context in which the NamingException was thrown and the exception that was thrown.",
      "tagMap": {
        "param": [
          "\u003ccode\u003esource\u003c/code\u003e - The non-null context in which the exception was thrown.",
          "\u003ccode\u003eexc\u003c/code\u003e - The non-null \n\u003ccode\u003eNamingException\u003c/code\u003e that was thrown."
        ]
      }
    }
  ],
  "memberType": "JavaClass",
  "modifiers": 1,
  "name": "javax.naming.event.NamingExceptionEvent",
  "comment": "This class represents an event fired when the procedures/processes used to collect information for notifying listeners of \n\u003ccode\u003eNamingEvent\u003c/code\u003es threw a \n\u003ccode\u003eNamingException\u003c/code\u003e. This can happen, for example, if the server which the listener is using aborts subsequent to the \n\u003ccode\u003eaddNamingListener()\u003c/code\u003e call.",
  "tagMap": {
    "see": [
      "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/event/NamingListener.html#namingExceptionThrown(javax.naming.event.NamingExceptionEvent)\"\u003e\u003ccode\u003eNamingListener.namingExceptionThrown(javax.naming.event.NamingExceptionEvent)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/event/EventContext.html\" title\u003d\"interface in javax.naming.event\"\u003e\u003ccode\u003eEventContext\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/serialized-form.html#javax.naming.event.NamingExceptionEvent\"\u003eSerialized Form\u003c/a\u003e"
    ],
    "since": [
      "1.3"
    ]
  }
}