{
  "packageName": "java.lang",
  "simpleName": "ExceptionInInitializerError",
  "moduleName": "java.base",
  "type": "CLASS",
  "superClass": {
    "name": "java.lang.LinkageError",
    "type": "Class"
  },
  "members": [
    {
      "returnType": {
        "name": "java.lang.Throwable",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getException",
      "comment": "Returns the exception that occurred during a static initialization that caused this error to be created. This method predates the general-purpose exception chaining facility. The Throwable.getCause() method is now the preferred means of obtaining this information.",
      "tagMap": {
        "return": [
          "the saved throwable object of this \n\u003ccode\u003eExceptionInInitializerError\u003c/code\u003e, or \n\u003ccode\u003enull\u003c/code\u003e if this \n\u003ccode\u003eExceptionInInitializerError\u003c/code\u003e has no saved throwable object."
        ]
      }
    },
    {
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs an ExceptionInInitializerError with null as its detail message string and with no saved throwable object. A detail message is a String that describes this particular exception.",
      "tagMap": {}
    },
    {
      "parameters": [
        {
          "type": {
            "name": "java.lang.Throwable",
            "type": "Class"
          },
          "field": {
            "name": "thrown"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs a new ExceptionInInitializerError class by saving a reference to the Throwable object thrown for later retrieval by the getException() method. The detail message string is set to null.",
      "tagMap": {
        "param": [
          "\u003ccode\u003ethrown\u003c/code\u003e - The exception thrown"
        ]
      }
    },
    {
      "parameters": [
        {
          "type": {
            "name": "java.lang.String",
            "type": "Class"
          },
          "field": {
            "name": "s"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs an ExceptionInInitializerError with the specified detail message string. A detail message is a String that describes this particular exception. The detail message string is saved for later retrieval by the Throwable.getMessage() method. There is no saved throwable object.",
      "tagMap": {
        "param": [
          "\u003ccode\u003es\u003c/code\u003e - the detail message"
        ]
      }
    }
  ],
  "memberType": "JavaClass",
  "modifiers": 1,
  "name": "java.lang.ExceptionInInitializerError",
  "comment": "Signals that an unexpected exception has occurred in a static initializer. An \n\u003ccode\u003eExceptionInInitializerError\u003c/code\u003e is thrown to indicate that an exception occurred during evaluation of a static initializer or the initializer for a static variable. \n\u003cp\u003eAs of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The \"saved throwable object\" that may be provided at construction time and accessed via the \u003ca href\u003d\"#getException()\"\u003e\u003ccode\u003egetException()\u003c/code\u003e\u003c/a\u003e method is now known as the \u003ci\u003ecause\u003c/i\u003e, and may be accessed via the \u003ca href\u003d\"Throwable.html#getCause()\"\u003e\u003ccode\u003eThrowable.getCause()\u003c/code\u003e\u003c/a\u003e method, as well as the aforementioned \"legacy method.\"\u003c/p\u003e",
  "tagMap": {
    "see": [
      "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/serialized-form.html#java.lang.ExceptionInInitializerError\"\u003eSerialized Form\u003c/a\u003e"
    ],
    "since": [
      "1.1"
    ]
  }
}