{
  "packageName": "java.nio.file",
  "simpleName": "DirectoryIteratorException",
  "moduleName": "java.base",
  "type": "CLASS",
  "superClass": {
    "name": "java.util.ConcurrentModificationException",
    "type": "Class"
  },
  "members": [
    {
      "returnType": {
        "name": "java.io.IOException",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getCause",
      "comment": "Returns the cause of this exception.",
      "tagMap": {
        "Overrides:": [
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html#getCause()\"\u003egetCause\u003c/a\u003e\u003c/code\u003e\u0026nbsp;in class\u0026nbsp;\n\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html\" title\u003d\"class in java.lang\"\u003eThrowable\u003c/a\u003e\u003c/code\u003e"
        ],
        "return": [
          "the cause"
        ]
      }
    },
    {
      "parameters": [
        {
          "type": {
            "name": "java.io.IOException",
            "type": "Class"
          },
          "field": {
            "name": "cause"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs an instance of this class.",
      "tagMap": {
        "param": [
          "\u003ccode\u003ecause\u003c/code\u003e - the \n\u003ccode\u003eIOException\u003c/code\u003e that caused the directory iteration to fail"
        ],
        "throws": [
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/NullPointerException.html\" title\u003d\"class in java.lang\"\u003eNullPointerException\u003c/a\u003e\u003c/code\u003e - if the cause is \n\u003ccode\u003enull\u003c/code\u003e"
        ]
      }
    }
  ],
  "memberType": "JavaClass",
  "modifiers": 17,
  "name": "java.nio.file.DirectoryIteratorException",
  "comment": "Runtime exception thrown if an I/O error is encountered when iterating over the entries in a directory. The I/O error is retrieved as an \n\u003ca href\u003d\"../../io/IOException.html\" title\u003d\"class in java.io\"\u003e\u003ccode\u003eIOException\u003c/code\u003e\u003c/a\u003e using the \n\u003ca href\u003d\"#getCause()\"\u003e\u003ccode\u003egetCause()\u003c/code\u003e\u003c/a\u003e method.",
  "tagMap": {
    "see": [
      "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/nio/file/DirectoryStream.html\" title\u003d\"interface in java.nio.file\"\u003e\u003ccode\u003eDirectoryStream\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/serialized-form.html#java.nio.file.DirectoryIteratorException\"\u003eSerialized Form\u003c/a\u003e"
    ],
    "since": [
      "1.7"
    ]
  }
}