{
  "packageName": "javax.naming",
  "simpleName": "NamingException",
  "moduleName": "java.naming",
  "type": "CLASS",
  "superClass": {
    "name": "java.lang.Exception",
    "type": "Class"
  },
  "members": [
    {
      "type": {
        "name": "javax.naming.Name",
        "type": "Class"
      },
      "memberType": "JavaField",
      "modifiers": 4,
      "name": "resolvedName",
      "comment": "Contains the part of the name that has been successfully resolved. It is a composite name and can be null. This field is initialized by the constructors. You should access and manipulate this field through its get and set methods.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getResolvedName()\"\u003e\u003ccode\u003egetResolvedName()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setResolvedName(javax.naming.Name)\"\u003e\u003ccode\u003esetResolvedName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e"
        ]
      }
    },
    {
      "type": {
        "name": "java.lang.Object",
        "type": "Class"
      },
      "memberType": "JavaField",
      "modifiers": 4,
      "name": "resolvedObj",
      "comment": "Contains the object to which resolution of the part of the name was successful. Can be null. This field is initialized by the constructors. You should access and manipulate this field through its get and set methods.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getResolvedObj()\"\u003e\u003ccode\u003egetResolvedObj()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setResolvedObj(java.lang.Object)\"\u003e\u003ccode\u003esetResolvedObj(java.lang.Object)\u003c/code\u003e\u003c/a\u003e"
        ]
      }
    },
    {
      "type": {
        "name": "javax.naming.Name",
        "type": "Class"
      },
      "memberType": "JavaField",
      "modifiers": 4,
      "name": "remainingName",
      "comment": "Contains the remaining name that has not been resolved yet. It is a composite name and can be null. This field is initialized by the constructors. You should access and manipulate this field through its get, set, \"append\" methods.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getRemainingName()\"\u003e\u003ccode\u003egetRemainingName()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003esetRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003eappendRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingComponent(java.lang.String)\"\u003e\u003ccode\u003eappendRemainingComponent(java.lang.String)\u003c/code\u003e\u003c/a\u003e"
        ]
      }
    },
    {
      "type": {
        "name": "java.lang.Throwable",
        "type": "Class"
      },
      "memberType": "JavaField",
      "modifiers": 4,
      "name": "rootException",
      "comment": "Contains the original exception that caused this NamingException to be thrown. This field is set if there is additional information that could be obtained from the original exception, or if the original exception could not be mapped to a subclass of NamingException. Can be null. This field predates the general-purpose exception chaining facility. The initCause(Throwable) and getCause() methods are now the preferred means of accessing this information.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getRootCause()\"\u003e\u003ccode\u003egetRootCause()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setRootCause(java.lang.Throwable)\"\u003e\u003ccode\u003esetRootCause(Throwable)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#initCause(java.lang.Throwable)\"\u003e\u003ccode\u003einitCause(Throwable)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getCause()\"\u003e\u003ccode\u003egetCause()\u003c/code\u003e\u003c/a\u003e"
        ]
      }
    },
    {
      "returnType": {
        "name": "javax.naming.Name",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getResolvedName",
      "comment": "Retrieves the leading portion of the name that was resolved successfully.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getResolvedObj()\"\u003e\u003ccode\u003egetResolvedObj()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setResolvedName(javax.naming.Name)\"\u003e\u003ccode\u003esetResolvedName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e"
        ],
        "return": [
          "The part of the name that was resolved successfully. It is a composite name. It can be null, which means the resolved name field has not been set."
        ]
      }
    },
    {
      "returnType": {
        "name": "javax.naming.Name",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getRemainingName",
      "comment": "Retrieves the remaining unresolved portion of the name.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003esetRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003eappendRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingComponent(java.lang.String)\"\u003e\u003ccode\u003eappendRemainingComponent(java.lang.String)\u003c/code\u003e\u003c/a\u003e"
        ],
        "return": [
          "The part of the name that has not been resolved. It is a composite name. It can be null, which means the remaining name field has not been set."
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.Object",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getResolvedObj",
      "comment": "Retrieves the object to which resolution was successful. This is the object to which the resolved name is bound.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getResolvedName()\"\u003e\u003ccode\u003egetResolvedName()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setResolvedObj(java.lang.Object)\"\u003e\u003ccode\u003esetResolvedObj(java.lang.Object)\u003c/code\u003e\u003c/a\u003e"
        ],
        "return": [
          "The possibly null object that was resolved so far. null means that the resolved object field has not been set."
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.String",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getExplanation",
      "comment": "Retrieves the explanation associated with this exception.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html#getMessage()\"\u003e\u003ccode\u003eThrowable.getMessage()\u003c/code\u003e\u003c/a\u003e"
        ],
        "return": [
          "The possibly null detail string explaining more about this exception. If null, it means there is no detail message for this exception."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "javax.naming.Name",
            "type": "Class"
          },
          "field": {
            "name": "name"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "setResolvedName",
      "comment": "Sets the resolved name field of this exception. name is a composite name. If the intent is to set this field using a compound name or string, you must \"stringify\" the compound name, and create a composite name with a single component using the string. You can then invoke this method using the resulting composite name. A copy of name is made and stored. Subsequent changes to name do not affect the copy in this NamingException and vice versa.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getResolvedName()\"\u003e\u003ccode\u003egetResolvedName()\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003ename\u003c/code\u003e - The possibly null name to set resolved name to. If null, it sets the resolved name field to null."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "javax.naming.Name",
            "type": "Class"
          },
          "field": {
            "name": "name"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "setRemainingName",
      "comment": "Sets the remaining name field of this exception. name is a composite name. If the intent is to set this field using a compound name or string, you must \"stringify\" the compound name, and create a composite name with a single component using the string. You can then invoke this method using the resulting composite name. A copy of name is made and stored. Subsequent changes to name do not affect the copy in this NamingException and vice versa.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getRemainingName()\"\u003e\u003ccode\u003egetRemainingName()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003eappendRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingComponent(java.lang.String)\"\u003e\u003ccode\u003eappendRemainingComponent(java.lang.String)\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003ename\u003c/code\u003e - The possibly null name to set remaining name to. If null, it sets the remaining name field to null."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "java.lang.Object",
            "type": "Class"
          },
          "field": {
            "name": "obj"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "setResolvedObj",
      "comment": "Sets the resolved object field of this exception.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getResolvedObj()\"\u003e\u003ccode\u003egetResolvedObj()\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003eobj\u003c/code\u003e - The possibly null object to set resolved object to. If null, the resolved object field is set to null."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "java.lang.String",
            "type": "Class"
          },
          "field": {
            "name": "name"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "appendRemainingComponent",
      "comment": "Add name as the last component in remaining name.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003esetRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getRemainingName()\"\u003e\u003ccode\u003egetRemainingName()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003eappendRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003ename\u003c/code\u003e - The component to add. If name is null, this method does not do anything."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "javax.naming.Name",
            "type": "Class"
          },
          "field": {
            "name": "name"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "appendRemainingName",
      "comment": "Add components from \u0027name\u0027 as the last components in remaining name. name is a composite name. If the intent is to append a compound name, you should \"stringify\" the compound name then invoke the overloaded form that accepts a String parameter. Subsequent changes to name do not affect the remaining name field in this NamingException and vice versa.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setRemainingName(javax.naming.Name)\"\u003e\u003ccode\u003esetRemainingName(javax.naming.Name)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getRemainingName()\"\u003e\u003ccode\u003egetRemainingName()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#appendRemainingComponent(java.lang.String)\"\u003e\u003ccode\u003eappendRemainingComponent(java.lang.String)\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003ename\u003c/code\u003e - The possibly null name containing ordered components to add. If name is null, this method does not do anything."
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.Throwable",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getRootCause",
      "comment": "Retrieves the root cause of this NamingException, if any. The root cause of a naming exception is used when the service provider wants to indicate to the caller a non-naming related exception but at the same time wants to use the NamingException structure to indicate how far the naming operation proceeded. This method predates the general-purpose exception chaining facility. The getCause() method is now the preferred means of obtaining this information.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#setRootCause(java.lang.Throwable)\"\u003e\u003ccode\u003esetRootCause(java.lang.Throwable)\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#rootException\"\u003e\u003ccode\u003erootException\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getCause()\"\u003e\u003ccode\u003egetCause()\u003c/code\u003e\u003c/a\u003e"
        ],
        "return": [
          "The possibly null exception that caused this naming exception. If null, it means no root cause has been set for this naming exception."
        ]
      }
    },
    {
      "returnType": {
        "name": "void",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "java.lang.Throwable",
            "type": "Class"
          },
          "field": {
            "name": "e"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "setRootCause",
      "comment": "Records the root cause of this NamingException. If e is this, this method does not do anything. This method predates the general-purpose exception chaining facility. The initCause(Throwable) method is now the preferred means of recording this information.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getRootCause()\"\u003e\u003ccode\u003egetRootCause()\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#rootException\"\u003e\u003ccode\u003erootException\u003c/code\u003e\u003c/a\u003e, \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#initCause(java.lang.Throwable)\"\u003e\u003ccode\u003einitCause(java.lang.Throwable)\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003ee\u003c/code\u003e - The possibly null exception that caused the naming operation to fail. If null, it means this naming exception has no root cause."
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.Throwable",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "getCause",
      "comment": "Returns the cause of this exception. The cause is the throwable that caused this naming exception to be thrown. Returns null if the cause is nonexistent or unknown.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#initCause(java.lang.Throwable)\"\u003e\u003ccode\u003einitCause(Throwable)\u003c/code\u003e\u003c/a\u003e"
        ],
        "Overrides:": [
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html#getCause()\"\u003egetCause\u003c/a\u003e\u003c/code\u003e\u0026nbsp;in class\u0026nbsp;\n\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html\" title\u003d\"class in java.lang\"\u003eThrowable\u003c/a\u003e\u003c/code\u003e"
        ],
        "return": [
          "the cause of this exception, or \n\u003ccode\u003enull\u003c/code\u003e if the cause is nonexistent or unknown."
        ],
        "since": [
          "1.4"
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.Throwable",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "java.lang.Throwable",
            "type": "Class"
          },
          "field": {
            "name": "cause"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "initCause",
      "comment": "Initializes the cause of this exception to the specified value. The cause is the throwable that caused this naming exception to be thrown. This method may be called at most once.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getCause()\"\u003e\u003ccode\u003egetCause()\u003c/code\u003e\u003c/a\u003e"
        ],
        "Overrides:": [
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html#initCause(java.lang.Throwable)\"\u003einitCause\u003c/a\u003e\u003c/code\u003e\u0026nbsp;in class\u0026nbsp;\n\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html\" title\u003d\"class in java.lang\"\u003eThrowable\u003c/a\u003e\u003c/code\u003e"
        ],
        "param": [
          "\u003ccode\u003ecause\u003c/code\u003e - the cause, which is saved for later retrieval by the \n\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.naming/javax/naming/NamingException.html#getCause()\"\u003e\u003ccode\u003egetCause()\u003c/code\u003e\u003c/a\u003e method. A \n\u003ccode\u003enull\u003c/code\u003e value indicates that the cause is nonexistent or unknown."
        ],
        "throws": [
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/IllegalArgumentException.html\" title\u003d\"class in java.lang\"\u003eIllegalArgumentException\u003c/a\u003e\u003c/code\u003e - if \n\u003ccode\u003ecause\u003c/code\u003e is this exception. (A throwable cannot be its own cause.)",
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/IllegalStateException.html\" title\u003d\"class in java.lang\"\u003eIllegalStateException\u003c/a\u003e\u003c/code\u003e - if this method has already been called on this exception."
        ],
        "return": [
          "a reference to this \n\u003ccode\u003eNamingException\u003c/code\u003e instance."
        ],
        "since": [
          "1.4"
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.String",
        "type": "Class"
      },
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "toString",
      "comment": "Generates the string representation of this exception. The string representation consists of this exception\u0027s class name, its detailed message, and if it has a root cause, the string representation of the root cause exception, followed by the remaining name (if it is not null). This string is used for debugging and not meant to be interpreted programmatically.",
      "tagMap": {
        "Overrides:": [
          "\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html#toString()\"\u003etoString\u003c/a\u003e\u003c/code\u003e\u0026nbsp;in class\u0026nbsp;\n\u003ccode\u003e\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html\" title\u003d\"class in java.lang\"\u003eThrowable\u003c/a\u003e\u003c/code\u003e"
        ],
        "return": [
          "The non-null string containing the string representation of this exception."
        ]
      }
    },
    {
      "returnType": {
        "name": "java.lang.String",
        "type": "Class"
      },
      "parameters": [
        {
          "type": {
            "name": "boolean",
            "type": "Class"
          },
          "field": {
            "name": "detail"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "name": "toString",
      "comment": "Generates the string representation in more detail. This string representation consists of the information returned by the toString() that takes no parameters, plus the string representation of the resolved object (if it is not null). This string is used for debugging and not meant to be interpreted programmatically.",
      "tagMap": {
        "param": [
          "\u003ccode\u003edetail\u003c/code\u003e - If true, include details about the resolved object in addition to the other information."
        ],
        "return": [
          "The non-null string containing the string representation."
        ]
      }
    },
    {
      "parameters": [
        {
          "type": {
            "name": "java.lang.String",
            "type": "Class"
          },
          "field": {
            "name": "explanation"
          }
        }
      ],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs a new NamingException with an explanation. All unspecified fields are set to null.",
      "tagMap": {
        "see": [
          "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Throwable.html#getMessage()\"\u003e\u003ccode\u003eThrowable.getMessage()\u003c/code\u003e\u003c/a\u003e"
        ],
        "param": [
          "\u003ccode\u003eexplanation\u003c/code\u003e - A possibly null string containing additional detail about this exception."
        ]
      }
    },
    {
      "parameters": [],
      "memberType": "JavaMethod",
      "modifiers": 1,
      "comment": "Constructs a new NamingException. All fields are set to null.",
      "tagMap": {}
    }
  ],
  "memberType": "JavaClass",
  "modifiers": 1,
  "name": "javax.naming.NamingException",
  "comment": "This is the superclass of all exceptions thrown by operations in the Context and DirContext interfaces. The nature of the failure is described by the name of the subclass. This exception captures the information pinpointing where the operation failed, such as where resolution last proceeded to. \n\u003cul\u003e \n \u003cli\u003e Resolved Name. Portion of name that has been resolved. \u003c/li\u003e\n \u003cli\u003e Resolved Object. Object to which resolution of name proceeded. \u003c/li\u003e\n \u003cli\u003e Remaining Name. Portion of name that has not been resolved. \u003c/li\u003e\n \u003cli\u003e Explanation. Detail explaining why name resolution failed. \u003c/li\u003e\n \u003cli\u003e Root Exception. The exception that caused this naming exception to be thrown. \u003c/li\u003e\n\u003c/ul\u003e null is an acceptable value for any of these fields. When null, it means that no such information has been recorded for that field. \n\u003cp\u003e A NamingException instance is not synchronized against concurrent multithreaded access. Multiple threads trying to access and modify a single NamingException instance should lock the object. \u003c/p\u003e\n\u003cp\u003e This exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The \u003ci\u003eroot exception\u003c/i\u003e (or \u003ci\u003eroot cause\u003c/i\u003e) is the same object as the \u003ci\u003ecause\u003c/i\u003e returned by the \u003ca href\u003d\"../../../java.base/java/lang/Throwable.html#getCause()\"\u003e\u003ccode\u003eThrowable.getCause()\u003c/code\u003e\u003c/a\u003e method.\u003c/p\u003e",
  "tagMap": {
    "see": [
      "\u003ca href\u003d\"https://docs.oracle.com/en/java/javase/16/docs/api/serialized-form.html#javax.naming.NamingException\"\u003eSerialized Form\u003c/a\u003e"
    ],
    "since": [
      "1.3"
    ]
  }
}